apiVersion: apps/v1
kind: Deployment
metadata:
  name: levelhome-fastapi
spec:
  selector:
    matchLabels:
      name: levelhome-fastapi
  template:
    metadata:
      labels:
        name: levelhome-fastapi
    spec:
      containers:
        - name: app
          image: 417722183802.dkr.ecr.us-west-2.amazonaws.com/levelhome:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: levelhome1.cmiih24acwxl.us-west-2.rds.amazonaws.com
            - name: POSTGRES_PORT
              value: 5432
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PWD
              value: postgres12345!
            - name: POSTGRES_DB
              value: levelhome1
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 0.0.0.0/0
